// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNOar8Bq_rqtzxKlKyPW6GsFJ3lp39DkI',
    appId: '1:321253167036:web:baa3eaa582b21ccf1965b9',
    messagingSenderId: '321253167036',
    projectId: 'car-shine-68e43',
    authDomain: 'car-shine-68e43.firebaseapp.com',
    storageBucket: 'car-shine-68e43.firebasestorage.app',
    measurementId: 'G-8XV65CKL03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFaP1W4Px9l5RTP8xHtZfeh_dSVHmBKDE',
    appId: '1:321253167036:android:c6e24a59615ad5251965b9',
    messagingSenderId: '321253167036',
    projectId: 'car-shine-68e43',
    storageBucket: 'car-shine-68e43.firebasestorage.app',
  );
}
